service: flady-card-app-service

frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - '@kingdarboja/serverless-plugin-typescript'
  - serverless-plugin-common-excludes
 
provider:
  name: aws
  runtime: nodejs16.x

package:  
  patterns:
    - node_modules/**

functions:
  nestjs:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}